### ISSUE TITLE
Cucumber Eclipes Plugin Snapshot updates site returns 404

### ISSUE THREAD

**Issue by imbur** [cucumber/cucumber-eclipse-update-site-snapshot#1]
Hello,

The Cucumber Plugin Snapshot update site has been giving a 404 lately [https://cucumber.github.io/cucumber-eclipse-update-site-snapshot](https://cucumber.github.io/cucumber-eclipse-update-site-snapshot).

I am aware that the plugin can still be installed from a local copy of the update site (which can be downloaded directly from this repo), so my intent with this ticket is to learn if it is intentional that the link above does not work anymore.

Thank you so much!

**Comment by qvdk** [comment]
Hi @imbur 

Sorry for the late response.

Even the site gives a 404 from your browser, the update site is working when you use it in the Eclipse Installation wizard.


![Screenshot from 2021-04-28 13-59-37](https://user-images.githubusercontent.com/6142398/116401169-33242900-a82b-11eb-9c64-f9bfd0af7f0f.png)
